# Generated by Django 4.2.4 on 2023-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
