# Generated by Django 4.2.4 on 2023-08-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='experience_date',
            field=models.DateField(default='1999-12-31', null=True, verbose_name='체험 날짜'),
        ),
    ]
