# Generated by Django 4.2.4 on 2023-08-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_memos_experience_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='district',
            field=models.TextField(default='', max_length=50, null=True, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='memos',
            name='platform',
            field=models.TextField(default='', max_length=150, null=True, verbose_name='플랫폼'),
        ),
        migrations.AddField(
            model_name='memos',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True, verbose_name='가격'),
        ),
    ]
