# Generated by Django 4.2.4 on 2023-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_memos_district_memos_platform_memos_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memos',
            name='text2',
        ),
        migrations.AddField(
            model_name='memos',
            name='tag_text',
            field=models.TextField(max_length=150, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='memos',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images', verbose_name='이미지'),
        ),
    ]
