# Generated by Django 4.2.4 on 2023-08-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_memos_keyword_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='keyword',
            field=models.IntegerField(default=0, null=True, verbose_name='키워드_비트연산'),
        ),
    ]
