# Generated by Django 4.2.4 on 2023-08-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_rename_update_date_memos_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='category',
            field=models.TextField(default='전체', max_length=50, null=True, verbose_name='카테고리'),
        ),
    ]
